---
- name: Install Nginx
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start and enable Nginx
  become: yes
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
