---
- name: Install Java
  become: yes
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Add Jenkins repo key
  become: yes
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins repo
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  become: yes
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable Jenkins
  become: yes
  ansible.builtin.systemd:
    name: jenkins
    enabled: yes
    state: started
