---
- name: Install docker dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker engine
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Ensure docker group exists
  become: yes
  group:
    name: docker
    state: present

- name: Add users to Docker group
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

- name: Enable and start Docker service
  become: yes
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
